--- what is the total revenue generated by male vs female customers 
select gender , sum(purchase_amount) as revenue
from customer_behavior
group by gender;

DROP TABLE IF EXISTS customer_behavior;

ALTER TABLE customer_behavior_new
RENAME TO customer_behavior;

SELECT table_name
FROM information_schema.tables
WHERE table_schema = 'public';


alter table customer_behavior
rename column "purchase_amount_(usd)" to purchase_amount;


SELECT column_name
FROM information_schema.columns
WHERE table_name = 'customer_behavior'
ORDER BY ordinal_position;


select*from customer_behavior;

----Q2-which customers used a discount but still spent more than the average purchase amount:
select customer_id ,purchase_amount
from customer_behavior
where discount_applied ='yes' and
purchase_amount >=(select avg(purchase_amount) from customer_behavior);


---Q3-which are the top 5 products with highest average review rating?
select item_purchased , round(avg(review_rating::numeric),2) as avg_review_rating
from customer_behavior
group by item_purchased
order by avg(review_rating) desc
limit 5;



---Q4-Compare the average products amounts between standard and Express Shipping
select shipping_type , avg(purchase_Amount)as avg_purchase_amount
from customer_behavior
where shipping_type in ('Express','Standard')
group by shipping_type;



---Q5-Do Subscribed customers spend more ? compare average spend and total revenue
---between subscribers and non-subscribers
select subscription_status,
count(customer_id) as total_customers
,avg(purchase_amount) as avg_spend
,sum(purchase_amount) as total_revenue
from customer_behavior
group by subscription_status
order by total_revenue
,avg_spend desc;



---Q6--Which 5 products have the highest percentage with discount applies?
select item_purchased, sum(case when discount_applied ='yes' then 1 else 0 end)/count(*) as discount_rate
from customer_behavior
group by item_purchased
order by discount_rate desc
limit 5;




--Q7-Segmemt customers into new ,returning ,and loyal based on thier toral
--number of previous purchases and show the count of each segment
with customer_type as(
select customer_id , previous_purchases,
case
when previous_purchases = 1 then 'New'
when previous_purchases between 2 and 10 then 'Returning'
else 'Loyal'
end as customer_segment
from customer_behavior
)
select customer_segment,count(*) as "number of customers "
from customer_type
group by customer_segment;


--Q8-What are the top 3 most purchased products within each category
with item_counts as(
select category , item_purchased,
count(customer_id) as total_orders,
row_number() over(partition by category order by count(customer_id)desc)
as item_rank
from customer_behavior
group by category,item_purchased
)
select item_rank , category,item_purchased,total_orders
from item_counts;





---Q9-Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status,count(customer_id) as repeat_buyers
from customer_behavior
where previous_purchases >5
group by subscription_status;




--Q10--What is the revenue contribution of each age group .
select age 
,sum(purchase_amount) as total_revenue
from customer_behavior_new
group by age
order by total_revenue desc;
